name : "Staging Action"

on: check_run
  type: [completed]

jobs:
  checkForSuccess:
    name: Success checks
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: arup-group/action-all-checks-passed@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
