name: "HTML Validation"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs: 
  analyze:

    name: HTML Validation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Perform HTML validation
        run: |
          python ../../tests/html_validator.py
        run: echo "W3C Validation job successfully ran! 🎉"
    
